export interface Regency {
  nama: string;
  kode: string;
}

export const REGENCIES: Regency[] = [
  {"nama": "KAB. ACEH BARAT", "kode": "D5"},
  {"nama": "KAB. ACEH BARAT DAYA", "kode": "D16"},
  {"nama": "KAB. ACEH BESAR", "kode": "D8"},
  {"nama": "KAB. ACEH JAYA", "kode": "D9"},
  {"nama": "KAB. ACEH SELATAN", "kode": "D22"},
  {"nama": "KAB. ACEH SINGKIL", "kode": "D17"},
  {"nama": "KAB. ACEH TAMIANG", "kode": "D18"},
  {"nama": "KAB. ACEH TENGAH", "kode": "D6"},
  {"nama": "KAB. ACEH TENGGARA", "kode": "D23"},
  {"nama": "KAB. ACEH TIMUR", "kode": "D24"},
  {"nama": "KAB. ACEH UTARA", "kode": "D4"},
  {"nama": "KAB. AGAM", "kode": "D472"},
  {"nama": "KAB. ALOR", "kode": "D320"},
  {"nama": "KAB. ASAHAN", "kode": "D503"},
  {"nama": "KAB. ASMAT", "kode": "D336"},
  {"nama": "KAB. BADUNG", "kode": "D26"},
  {"nama": "KAB. BALANGAN", "kode": "D215"},
  {"nama": "KAB. BANDUNG", "kode": "D107"},
  {"nama": "KAB. BANDUNG BARAT", "kode": "D102"},
  {"nama": "KAB. BANGGAI", "kode": "D427"},
  {"nama": "KAB. BANGGAI KEPULAUAN", "kode": "D432"},
  {"nama": "KAB. BANGGAI LAUT", "kode": "D551"},
  {"nama": "KAB. BANGKA", "kode": "D36"},
  {"nama": "KAB. BANGKA BARAT", "kode": "D42"},
  {"nama": "KAB. BANGKALAN", "kode": "D195"},
  {"nama": "KAB. BANGKA SELATAN", "kode": "D39"},
  {"nama": "KAB. BANGKA TENGAH", "kode": "D37"},
  {"nama": "KAB. BANGLI", "kode": "D29"},
  {"nama": "KAB. BANJAR", "kode": "D213"},
  {"nama": "KAB. BANJARNEGARA", "kode": "D131"},
  {"nama": "KAB. BANTAENG", "kode": "D404"},
  {"nama": "KAB. BANTUL", "kode": "D68"},
  {"nama": "KAB. BANYUASIN", "kode": "D483"},
  {"nama": "KAB. BANYUMAS", "kode": "D124"},
  {"nama": "KAB. BANYUWANGI", "kode": "D159"},
  {"nama": "KAB. BARITO KUALA", "kode": "D223"},
  {"nama": "KAB. BARITO SELATAN", "kode": "D233"},
  {"nama": "KAB. BARITO TIMUR", "kode": "D234"},
  {"nama": "KAB. BARITO UTARA", "kode": "D232"},
  {"nama": "KAB. BARRU", "kode": "D417"},
  {"nama": "KAB. BATANG", "kode": "D136"},
  {"nama": "KAB. BATANGHARI", "kode": "D85"},
  {"nama": "KAB. BATU BARA", "kode": "D504"},
  {"nama": "KAB. BEKASI", "kode": "D115"},
  {"nama": "KAB. BELITUNG", "kode": "D40"},
  {"nama": "KAB. BELITUNG TIMUR", "kode": "D41"},
  {"nama": "KAB. BELU", "kode": "D316"},
  {"nama": "KAB. BENER MERIAH", "kode": "D21"},
  {"nama": "KAB. BENGKALIS", "kode": "D381"},
  {"nama": "KAB. BENGKAYANG", "kode": "D206"},
  {"nama": "KAB. BENGKULU SELATAN", "kode": "D56"},
  {"nama": "KAB. BENGKULU TENGAH", "kode": "D60"},
  {"nama": "KAB. BENGKULU UTARA", "kode": "D53"},
  {"nama": "KAB. BERAU", "kode": "D242"},
  {"nama": "KAB. BIAK NUMFOR", "kode": "D344"},
  {"nama": "KAB. BIMA", "kode": "D311"},
  {"nama": "KAB. BINTAN", "kode": "D262"},
  {"nama": "KAB. BIREUEN", "kode": "D10"},
  {"nama": "KAB. BLITAR", "kode": "D169"},
  {"nama": "KAB. BLORA", "kode": "D126"},
  {"nama": "KAB. BOALEMO", "kode": "D79"},
  {"nama": "KAB. BOGOR", "kode": "D108"},
  {"nama": "KAB. BOJONEGORO", "kode": "D171"},
  {"nama": "KAB. BOLAANG MONGONDOW", "kode": "D453"},
  {"nama": "KAB. BOLAANG MONGONDOW SELATAN", "kode": "D532"},
  {"nama": "KAB. BOLAANG MONGONDOW TIMUR", "kode": "D454"},
  {"nama": "KAB. BOLAANG MONGONDOW UTARA", "kode": "D455"},
  {"nama": "KAB. BOMBANA", "kode": "D441"},
  {"nama": "KAB. BONDOWOSO", "kode": "D190"},
  {"nama": "KAB. BONE", "kode": "D410"},
  {"nama": "KAB. BONE BOLANGO", "kode": "D77"},
  {"nama": "KAB. BOVEN DIGOEL", "kode": "D345"},
  {"nama": "KAB. BOYOLALI", "kode": "D137"},
  {"nama": "KAB. BREBES", "kode": "D123"},
  {"nama": "KAB. BULELENG", "kode": "D30"},
  {"nama": "KAB. BULUKUMBA", "kode": "D411"},
  {"nama": "KAB. BULUNGAN", "kode": "D248"},
  {"nama": "KAB. BUNGO", "kode": "D94"},
  {"nama": "KAB. BUOL", "kode": "D429"},
  {"nama": "KAB. BURU", "kode": "D280"},
  {"nama": "KAB. BURU SELATAN", "kode": "D289"},
  {"nama": "KAB. BUTON", "kode": "D435"},
  {"nama": "KAB. BUTON SELATAN", "kode": "D549"},
  {"nama": "KAB. BUTON TENGAH", "kode": "D548"},
  {"nama": "KAB. BUTON UTARA", "kode": "D437"},
  {"nama": "KAB. CIAMIS", "kode": "D116"},
  {"nama": "KAB. CIANJUR", "kode": "D117"},
  {"nama": "KAB. CILACAP", "kode": "D135"},
  {"nama": "KAB. CIREBON", "kode": "D103"},
  {"nama": "KAB. DAIRI", "kode": "D505"},
  {"nama": "KAB. DEIYAI", "kode": "D362"},
  {"nama": "KAB. DELI SERDANG", "kode": "D506"},
  {"nama": "KAB. DEMAK", "kode": "D154"},
  {"nama": "KAB. DHARMASRAYA", "kode": "D466"},
  {"nama": "KAB. DOGIYAI", "kode": "D346"},
  {"nama": "KAB. DOMPU", "kode": "N1"},
  {"nama": "KAB. DONGGALA", "kode": "D422"},
  {"nama": "KAB. EMPAT LAWANG", "kode": "D491"},
  {"nama": "KAB. ENDE", "kode": "D313"},
  {"nama": "KAB. ENREKANG", "kode": "D399"},
  {"nama": "KAB. FAK FAK", "kode": "D367"},
  {"nama": "KAB. FLORES TIMUR", "kode": "D331"},
  {"nama": "KAB. GARUT", "kode": "D105"},
  {"nama": "KAB. GAYO LUES", "kode": "D19"},
  {"nama": "KAB. GIANYAR", "kode": "D31"},
  {"nama": "KAB. GORONTALO", "kode": "D81"},
  {"nama": "KAB. GORONTALO UTARA", "kode": "D80"},
  {"nama": "KAB. GOWA", "kode": "D409"},
  {"nama": "KAB. GRESIK", "kode": "D168"},
  {"nama": "KAB. GROBOGAN", "kode": "D144"},
  {"nama": "KAB. GUNUNGKIDUL", "kode": "D65"},
  {"nama": "KAB. GUNUNG MAS", "kode": "D235"},
  {"nama": "KAB. HALMAHERA BARAT", "kode": "D296"},
  {"nama": "KAB. HALMAHERA SELATAN", "kode": "D295"},
  {"nama": "KAB. HALMAHERA TENGAH", "kode": "D294"},
  {"nama": "KAB. HALMAHERA TIMUR", "kode": "D297"},
  {"nama": "KAB. HALMAHERA UTARA", "kode": "D292"},
  {"nama": "KAB. HULU SUNGAI SELATAN", "kode": "D221"},
  {"nama": "KAB. HULU SUNGAI TENGAH", "kode": "D224"},
  {"nama": "KAB. HULU SUNGAI UTARA", "kode": "D217"},
  {"nama": "KAB. HUMBANG HASUNDUTAN", "kode": "D507"},
  {"nama": "KAB. INDRAGIRI HILIR", "kode": "D379"},
  {"nama": "KAB. INDRAGIRI HULU", "kode": "D388"},
  {"nama": "KAB. INDRAMAYU", "kode": "D96"},
  {"nama": "KAB. INTAN JAYA", "kode": "D363"},
  {"nama": "KAB. JAYAPURA", "kode": "D337"},
  {"nama": "KAB. JAYAWIJAYA", "kode": "D347"},
  {"nama": "KAB. JEMBER", "kode": "D172"},
  {"nama": "KAB. JEMBRANA", "kode": "D28"},
  {"nama": "KAB. JENEPONTO", "kode": "D418"},
  {"nama": "KAB. JEPARA", "kode": "D134"},
  {"nama": "KAB. JOMBANG", "kode": "D164"},
  {"nama": "KAB. KAIMANA", "kode": "D368"},
  {"nama": "KAB. KAMPAR", "kode": "D380"},
  {"nama": "KAB. KAPUAS", "kode": "D239"},
  {"nama": "KAB. KAPUAS HULU", "kode": "D209"},
  {"nama": "KAB. KARANGANYAR", "kode": "D125"},
  {"nama": "KAB. KARANGASEM", "kode": "D34"},
  {"nama": "KAB. KARAWANG", "kode": "D98"},
  {"nama": "KAB. KARIMUN", "kode": "D258"},
  {"nama": "KAB. KARO", "kode": "D521"},
  {"nama": "KAB. KATINGAN", "kode": "D236"},
  {"nama": "KAB. KAUR", "kode": "D61"},
  {"nama": "KAB. KAYONG UTARA", "kode": "D207"},
  {"nama": "KAB. KEBUMEN", "kode": "D128"},
  {"nama": "KAB. KEDIRI", "kode": "D173"},
  {"nama": "KAB. KEEROM", "kode": "D338"},
  {"nama": "KAB. KENDAL", "kode": "D155"},
  {"nama": "KAB. KEPAHIANG", "kode": "D58"},
  {"nama": "KAB. KEP. SIAU TAGULANDANG BIARO", "kode": "D447"},
  {"nama": "KAB. KEPULAUAN ANAMBAS", "kode": "D263"},
  {"nama": "KAB. KEPULAUAN ARU", "kode": "D288"},
  {"nama": "KAB. KEPULAUAN MENTAWAI", "kode": "D481"},
  {"nama": "KAB. KEPULAUAN MERANTI", "kode": "D386"},
  {"nama": "KAB. KEPULAUAN SANGIHE", "kode": "D458"},
  {"nama": "KAB. KEPULAUAN SELAYAR", "kode": "D412"},
  {"nama": "KAB. KEPULAUAN SULA", "kode": "D298"},
  {"nama": "KAB. KEPULAUAN TALAUD", "kode": "D457"},
  {"nama": "KAB. KEPULAUAN TANIMBAR", "kode": "D284"},
  {"nama": "KAB. KEPULAUAN YAPEN", "kode": "D348"},
  {"nama": "KAB. KERINCI", "kode": "D86"},
  {"nama": "KAB. KETAPANG", "kode": "D201"},
  {"nama": "KAB. KLATEN", "kode": "D141"},
  {"nama": "KAB. KLUNGKUNG", "kode": "D32"},
  {"nama": "KAB. KOLAKA", "kode": "D444"},
  {"nama": "KAB. KOLAKA TIMUR", "kode": "D537"},
  {"nama": "KAB. KOLAKA UTARA", "kode": "D442"},
  {"nama": "KAB. KONAWE", "kode": "D445"},
  {"nama": "KAB. KONAWE KEPULAUAN", "kode": "D538"},
  {"nama": "KAB. KONAWE SELATAN", "kode": "D438"},
  {"nama": "KAB. KONAWE UTARA", "kode": "D439"},
  {"nama": "KAB. KOTABARU", "kode": "D225"},
  {"nama": "KAB. KOTAWARINGIN BARAT", "kode": "D228"},
  {"nama": "KAB. KOTAWARINGIN TIMUR", "kode": "D227"},
  {"nama": "KAB. KUANTAN SINGINGI", "kode": "D378"},
  {"nama": "KAB. KUBU RAYA", "kode": "D202"},
  {"nama": "KAB. KUDUS", "kode": "D145"},
  {"nama": "KAB. KULON PROGO", "kode": "D66"},
  {"nama": "KAB. KUNINGAN", "kode": "D106"},
  {"nama": "KAB. KUPANG", "kode": "D322"},
  {"nama": "KAB. KUTAI BARAT", "kode": "D255"},
  {"nama": "KAB. KUTAI KARTANEGARA", "kode": "D246"},
  {"nama": "KAB. KUTAI TIMUR", "kode": "D252"},
  {"nama": "KAB. LABUHANBATU", "kode": "D499"},
  {"nama": "KAB. LABUHANBATU SELATAN", "kode": "D508"},
  {"nama": "KAB. LABUHANBATU UTARA", "kode": "D525"},
  {"nama": "KAB. LAHAT", "kode": "D497"},
  {"nama": "KAB. LAMANDAU", "kode": "D229"},
  {"nama": "KAB. LAMONGAN", "kode": "D174"},
  {"nama": "KAB. LAMPUNG BARAT", "kode": "D270"},
  {"nama": "KAB. LAMPUNG SELATAN", "kode": "D267"},
  {"nama": "KAB. LAMPUNG TENGAH", "kode": "D273"},
  {"nama": "KAB. LAMPUNG TIMUR", "kode": "D268"},
  {"nama": "KAB. LAMPUNG UTARA", "kode": "D271"},
  {"nama": "KAB. LANDAK", "kode": "D205"},
  {"nama": "KAB. LANGKAT", "kode": "D519"},
  {"nama": "KAB. LANNY JAYA", "kode": "D349"},
  {"nama": "KAB. LEBAK", "kode": "D45"},
  {"nama": "KAB. LEBONG", "kode": "D54"},
  {"nama": "KAB. LEMBATA", "kode": "D332"},
  {"nama": "KAB. LIMA PULUH KOTA", "kode": "D476"},
  {"nama": "KAB. LINGGA", "kode": "D261"},
  {"nama": "KAB. LOMBOK BARAT", "kode": "D307"},
  {"nama": "KAB. LOMBOK TENGAH", "kode": "D304"},
  {"nama": "KAB. LOMBOK TIMUR", "kode": "D305"},
  {"nama": "KAB. LOMBOK UTARA", "kode": "D308"},
  {"nama": "KAB. LUMAJANG", "kode": "D183"},
  {"nama": "KAB. LUWU", "kode": "D407"},
  {"nama": "KAB. LUWU TIMUR", "kode": "D408"},
  {"nama": "KAB. LUWU UTARA", "kode": "D396"},
  {"nama": "KAB. MADIUN", "kode": "D161"},
  {"nama": "KAB. MAGELANG", "kode": "D146"},
  {"nama": "KAB. MAGETAN", "kode": "D165"},
  {"nama": "KAB. MAHAKAM ULU", "kode": "D534"},
  {"nama": "KAB. MAJALENGKA", "kode": "D100"},
  {"nama": "KAB. MAJENE", "kode": "D392"},
  {"nama": "KAB. MALAKA", "kode": "D535"},
  {"nama": "KAB. MALANG", "kode": "D166"},
  {"nama": "KAB. MALINAU", "kode": "D253"},
  {"nama": "KAB. MALUKU BARAT DAYA", "kode": "D290"},
  {"nama": "KAB. MALUKU TENGAH", "kode": "D287"},
  {"nama": "KAB. MALUKU TENGGARA", "kode": "D282"},
  {"nama": "KAB. MAMASA", "kode": "D394"},
  {"nama": "KAB. MAMBERAMO RAYA", "kode": "D350"},
  {"nama": "KAB. MAMBERAMO TENGAH", "kode": "D351"},
  {"nama": "KAB. MAMUJU", "kode": "D390"},
  {"nama": "KAB. MAMUJU TENGAH", "kode": "D547"},
  {"nama": "KAB. MANDAILING NATAL", "kode": "D509"},
  {"nama": "KAB. MANGGARAI", "kode": "D319"},
  {"nama": "KAB. MANGGARAI BARAT", "kode": "D321"},
  {"nama": "KAB. MANGGARAI TIMUR", "kode": "D327"},
  {"nama": "KAB. MANOKWARI", "kode": "D365"},
  {"nama": "KAB. MANOKWARI SELATAN", "kode": "D544"},
  {"nama": "KAB. MAPPI", "kode": "D339"},
  {"nama": "KAB. MAROS", "kode": "D397"},
  {"nama": "KAB. MAYBRAT", "kode": "D374"},
  {"nama": "KAB. MELAWI", "kode": "D210"},
  {"nama": "KAB. MEMPAWAH", "kode": "D552"},
  {"nama": "KAB. MERANGIN", "kode": "D90"},
  {"nama": "KAB. MERAUKE", "kode": "D335"},
  {"nama": "KAB. MESUJI", "kode": "D276"},
  {"nama": "KAB. MIMIKA", "kode": "D340"},
  {"nama": "KAB. MINAHASA", "kode": "D461"},
  {"nama": "KAB. MINAHASA SELATAN", "kode": "D459"},
  {"nama": "KAB. MINAHASA TENGGARA", "kode": "D451"},
  {"nama": "KAB. MINAHASA UTARA", "kode": "D448"},
  {"nama": "KAB. MOJOKERTO", "kode": "D170"},
  {"nama": "KAB. MOROWALI", "kode": "D426"},
  {"nama": "KAB. MOROWALI UTARA", "kode": "D541"},
  {"nama": "KAB. MUARA ENIM", "kode": "D485"},
  {"nama": "KAB. MUARO JAMBI", "kode": "D87"},
  {"nama": "KAB. MUKO MUKO", "kode": "D57"},
  {"nama": "KAB. MUNA", "kode": "D443"},
  {"nama": "KAB. MUNA BARAT", "kode": "D543"},
  {"nama": "KAB. MURUNG RAYA", "kode": "D240"},
  {"nama": "KAB. MUSI BANYUASIN", "kode": "D488"},
  {"nama": "KAB. MUSI RAWAS", "kode": "D492"},
  {"nama": "KAB. MUSI RAWAS UTARA", "kode": "D540"},
  {"nama": "KAB. NABIRE", "kode": "D341"},
  {"nama": "KAB. NAGAN RAYA", "kode": "D11"},
  {"nama": "KAB. NAGAN REY", "kode": "D11"},
  {"nama": "KAB. NAGEKEO", "kode": "D326"},
  {"nama": "KAB. NATUNA", "kode": "D260"},
  {"nama": "KAB. NDUGA", "kode": "D550"},
  {"nama": "KAB. NGADA", "kode": "D325"},
  {"nama": "KAB. NGANJUK", "kode": "D167"},
  {"nama": "KAB. NGAWI", "kode": "D175"},
  {"nama": "KAB. NIAS", "kode": "D527"},
  {"nama": "KAB. NIAS BARAT", "kode": "D523"},
  {"nama": "KAB. NIAS SELATAN", "kode": "D510"},
  {"nama": "KAB. NIAS UTARA", "kode": "D528"},
  {"nama": "KAB. NUNUKAN", "kode": "D250"},
  {"nama": "KAB. OGAN ILIR", "kode": "D496"},
  {"nama": "KAB. OGAN KOMERING ILIR", "kode": "D489"},
  {"nama": "KAB. OGAN KOMERING ULU", "kode": "D495"},
  {"nama": "KAB. OGAN KOMERING ULU SELATAN", "kode": "D493"},
  {"nama": "KAB. OGAN KOMERING ULU TIMUR", "kode": "D494"},
  {"nama": "KAB. PACITAN", "kode": "D163"},
  {"nama": "KAB. PADANG LAWAS", "kode": "D511"},
  {"nama": "KAB. PADANG LAWAS UTARA", "kode": "D530"},
  {"nama": "KAB. PADANG PARIAMAN", "kode": "D473"},
  {"nama": "KAB. PAKPAK BHARAT", "kode": "D512"},
  {"nama": "KAB. PAMEKASAN", "kode": "D193"},
  {"nama": "KAB. PANDEGLANG", "kode": "D51"},
  {"nama": "KAB. PANGANDARAN", "kode": "D536"},
  {"nama": "KAB. PANGKAJENE KEPULAUAN", "kode": "D405"},
  {"nama": "KAB. PANIAI", "kode": "D353"},
  {"nama": "KAB. PARIGI MOUTONG", "kode": "D423"},
  {"nama": "KAB. PASAMAN", "kode": "D467"},
  {"nama": "KAB. PASAMAN BARAT", "kode": "D477"},
  {"nama": "KAB. PASANGKAYU", "kode": "D393"},
  {"nama": "KAB. PASER", "kode": "D247"},
  {"nama": "KAB. PASURUAN", "kode": "D185"},
  {"nama": "KAB. PATI", "kode": "D156"},
  {"nama": "KAB. PEGUNUNGAN ARFAK", "kode": "D545"},
  {"nama": "KAB. PEGUNUNGAN BINTANG", "kode": "D354"},
  {"nama": "KAB. PEKALONGAN", "kode": "D132"},
  {"nama": "KAB. PELALAWAN", "kode": "D382"},
  {"nama": "KAB. PEMALANG", "kode": "D133"},
  {"nama": "KAB. PENAJAM PASER UTARA", "kode": "D244"},
  {"nama": "KAB. PENUKAL ABAB LEMATANG ILIR", "kode": "D911"},
  {"nama": "KAB. PESAWARAN", "kode": "D265"},
  {"nama": "KAB. PESISIR BARAT", "kode": "D539"},
  {"nama": "KAB. PESISIR SELATAN", "kode": "D464"},
  {"nama": "KAB. PIDIE", "kode": "D12"},
  {"nama": "KAB. PIDIE JAYA", "kode": "D13"},
  {"nama": "KAB. PINRANG", "kode": "D400"},
  {"nama": "KAB. POHUWATO", "kode": "D78"},
  {"nama": "KAB. POLEWALI MANDAR", "kode": "D391"},
  {"nama": "KAB. PONOROGO", "kode": "D196"},
  {"nama": "KAB. POSO", "kode": "D428"},
  {"nama": "KAB. PRINGSEWU", "kode": "D278"},
  {"nama": "KAB. PROBOLINGGO", "kode": "D182"},
  {"nama": "KAB. PULANG PISAU", "kode": "D238"},
  {"nama": "KAB. PULAU MOROTAI", "kode": "D542"},
  {"nama": "KAB. PULAU TALIABU", "kode": "D546"},
  {"nama": "KAB. PUNCAK", "kode": "D355"},
  {"nama": "KAB. PUNCAK JAYA", "kode": "D342"},
  {"nama": "KAB. PURBALINGGA", "kode": "D149"},
  {"nama": "KAB. PURWAKARTA", "kode": "D109"},
  {"nama": "KAB. PURWOREJO", "kode": "D130"},
  {"nama": "KAB. RAJA AMPAT", "kode": "D369"},
  {"nama": "KAB. REJANG LEBONG", "kode": "D59"},
  {"nama": "KAB. REMBANG", "kode": "D157"},
  {"nama": "KAB. ROKAN HILIR", "kode": "D387"},
  {"nama": "KAB. ROKAN HULU", "kode": "D383"},
  {"nama": "KAB. ROTE NDAO", "kode": "D323"},
  {"nama": "KAB. SABU RAIJUA", "kode": "D333"},
  {"nama": "KAB. SAMBAS", "kode": "D208"},
  {"nama": "KAB. SAMOSIR", "kode": "D513"},
  {"nama": "KAB. SAMPANG", "kode": "D186"},
  {"nama": "KAB. SANGGAU", "kode": "D204"},
  {"nama": "KAB. SARMI", "kode": "D356"},
  {"nama": "KAB. SAROLANGUN", "kode": "D84"},
  {"nama": "KAB. SEKADAU", "kode": "D198"},
  {"nama": "KAB. SELUMA", "kode": "D62"},
  {"nama": "KAB. SEMARANG", "kode": "D138"},
  {"nama": "KAB. SERAM BAGIAN BARAT", "kode": "D283"},
  {"nama": "KAB. SERAM BAGIAN TIMUR", "kode": "D286"},
  {"nama": "KAB. SERANG", "kode": "D48"},
  {"nama": "KAB. SERDANG BEDAGAI", "kode": "D518"},
  {"nama": "KAB. SERUYAN", "kode": "D230"},
  {"nama": "KAB. SIAK", "kode": "D384"},
  {"nama": "KAB. SIDENRENG RAPPANG", "kode": "D406"},
  {"nama": "KAB. SIDOARJO", "kode": "D160"},
  {"nama": "KAB. SIGI", "kode": "D431"},
  {"nama": "KAB. SIJUNJUNG", "kode": "D463"},
  {"nama": "KAB. SIKKA", "kode": "D328"},
  {"nama": "KAB. SIMALUNGUN", "kode": "D522"},
  {"nama": "KAB. SIMEULUE", "kode": "D15"},
  {"nama": "KAB. SINJAI", "kode": "D401"},
  {"nama": "KAB. SINTANG", "kode": "D211"},
  {"nama": "KAB. SITUBONDO", "kode": "D176"},
  {"nama": "KAB. SLEMAN", "kode": "D67"},
  {"nama": "KAB. SOLOK", "kode": "D475"},
  {"nama": "KAB. SOLOK SELATAN", "kode": "D478"},
  {"nama": "KAB. SOPPENG", "kode": "D414"},
  {"nama": "KAB. SORONG", "kode": "D370"},
  {"nama": "KAB. SORONG SELATAN", "kode": "D371"},
  {"nama": "KAB. SRAGEN", "kode": "D139"},
  {"nama": "KAB. SUBANG", "kode": "D120"},
  {"nama": "KAB. SUKABUMI", "kode": "D121"},
  {"nama": "KAB. SUKAMARA", "kode": "D237"},
  {"nama": "KAB. SUKOHARJO", "kode": "D150"},
  {"nama": "KAB. SUMBA BARAT", "kode": "D314"},
  {"nama": "KAB. SUMBA BARAT DAYA", "kode": "D315"},
  {"nama": "KAB. SUMBA TENGAH", "kode": "D329"},
  {"nama": "KAB. SUMBA TIMUR", "kode": "D330"},
  {"nama": "KAB. SUMBAWA", "kode": "D303"},
  {"nama": "KAB. SUMBAWA BARAT", "kode": "D302"},
  {"nama": "KAB. SUMEDANG", "kode": "D118"},
  {"nama": "KAB. SUMENEP", "kode": "D162"},
  {"nama": "KAB. SUPIORI", "kode": "D357"},
  {"nama": "KAB. TABALONG", "kode": "D219"},
  {"nama": "KAB. TABANAN", "kode": "D33"},
  {"nama": "KAB. TAKALAR", "kode": "D413"},
  {"nama": "KAB. TAMBRAUW", "kode": "D373"},
  {"nama": "KAB. TANAH BUMBU", "kode": "D222"},
  {"nama": "KAB. TANAH DATAR", "kode": "D465"},
  {"nama": "KAB. TANAH LAUT", "kode": "D218"},
  {"nama": "KAB. TANA TIDUNG", "kode": "D254"},
  {"nama": "KAB. TANA TORAJA", "kode": "D419"},
  {"nama": "KAB. TANGERANG", "kode": "D50"},
  {"nama": "KAB. TANGGAMUS", "kode": "D277"},
  {"nama": "KAB. TANJUNG JABUNG BARAT", "kode": "D88"},
  {"nama": "KAB. TANJUNG JABUNG TIMUR", "kode": "D93"},
  {"nama": "KAB. TAPANULI SELATAN", "kode": "D529"},
  {"nama": "KAB. TAPANULI TENGAH", "kode": "D524"},
  {"nama": "KAB. TAPANULI UTARA", "kode": "D500"},
  {"nama": "KAB. TAPIN", "kode": "D220"},
  {"nama": "KAB. TASIKMALAYA", "kode": "D110"},
  {"nama": "KAB. TEBO", "kode": "D92"},
  {"nama": "KAB. TEGAL", "kode": "D142"},
  {"nama": "KAB. TELUK BINTUNI", "kode": "D372"},
  {"nama": "KAB. TELUK WONDAMA", "kode": "D375"},
  {"nama": "KAB. TEMANGGUNG", "kode": "D140"},
  {"nama": "KAB. TIMOR TENGAH SELATAN", "kode": "D324"},
  {"nama": "KAB. TIMOR TENGAH UTARA", "kode": "D318"},
  {"nama": "KAB. TOBA", "kode": "D520"},
  {"nama": "KAB. TOJO UNA UNA", "kode": "D424"},
  {"nama": "KAB. TOLIKARA", "kode": "D358"},
  {"nama": "KAB. TOLI TOLI", "kode": "D430"},
  {"nama": "KAB. TORAJA UTARA", "kode": "D416"},
  {"nama": "KAB. TRENGGALEK", "kode": "D192"},
  {"nama": "KAB. TUBAN", "kode": "D189"},
  {"nama": "KAB. TULANG BAWANG", "kode": "D275"},
  {"nama": "KAB. TULANG BAWANG BARAT", "kode": "D274"},
  {"nama": "KAB. TULUNGAGUNG", "kode": "D194"},
  {"nama": "KAB. WAJO", "kode": "D415"},
  {"nama": "KAB. WAKATOBI", "kode": "D440"},
  {"nama": "KAB. WAROPEN", "kode": "D359"},
  {"nama": "KAB. WAY KANAN", "kode": "D272"},
  {"nama": "KAB. WONOGIRI", "kode": "D153"},
  {"nama": "KAB. WONOSOBO", "kode": "D151"},
  {"nama": "KAB. YAHUKIMO", "kode": "D360"},
  {"nama": "KAB. YALIMO", "kode": "D361"}
];
