export interface City {
  nama: string;
  kode: string;
}

export const CITIES: City[] = [
  {"nama": "KOTA AMBON", "kode": "D281"},
  {"nama": "KOTA BALIKPAPAN", "kode": "D249"},
  {"nama": "KOTA BANDA ACEH", "kode": "D2"},
  {"nama": "KOTA BANDAR LAMPUNG", "kode": "D269"},
  {"nama": "KOTA BANDUNG", "kode": "D99"},
  {"nama": "KOTA BANJAR", "kode": "D119"},
  {"nama": "KOTA BANJARBARU", "kode": "D216"},
  {"nama": "KOTA BANJARMASIN", "kode": "D214"},
  {"nama": "KOTA BATAM", "kode": "D257"},
  {"nama": "KOTA BATU", "kode": "D177"},
  {"nama": "KOTA BAU BAU", "kode": "D436"},
  {"nama": "KOTA BEKASI", "kode": "D114"},
  {"nama": "KOTA BENGKULU", "kode": "D55"},
  {"nama": "KOTA BIMA", "kode": "D310"},
  {"nama": "KOTA BINJAI", "kode": "D517"},
  {"nama": "KOTA BITUNG", "kode": "D460"},
  {"nama": "KOTA BLITAR", "kode": "D178"},
  {"nama": "KOTA BOGOR", "kode": "D101"},
  {"nama": "KOTA BONTANG", "kode": "D251"},
  {"nama": "KOTA BUKITTINGGI", "kode": "D479"},
  {"nama": "KOTA CILEGON", "kode": "D49"},
  {"nama": "KOTA CIMAHI", "kode": "D111"},
  {"nama": "KOTA CIREBON", "kode": "D112"},
  {"nama": "KOTA DENPASAR", "kode": "D27"},
  {"nama": "KOTA DEPOK", "kode": "D97"},
  {"nama": "KOTA DUMAI", "kode": "D385"},
  {"nama": "KOTA GORONTALO", "kode": "D82"},
  {"nama": "KOTA GUNUNGSITOLI", "kode": "D526"},
  {"nama": "KOTA JAMBI", "kode": "D89"},
  {"nama": "KOTA JAYAPURA", "kode": "D343"},
  {"nama": "KOTA KEDIRI", "kode": "D187"},
  {"nama": "KOTA KENDARI", "kode": "D434"},
  {"nama": "KOTA KOTAMOBAGU", "kode": "D449"},
  {"nama": "KOTA KUPANG", "kode": "D317"},
  {"nama": "KOTA LANGSA", "kode": "D14"},
  {"nama": "KOTA LHOKSEUMAWE", "kode": "D3"},
  {"nama": "KOTA LUBUK LINGGAU", "kode": "D490"},
  {"nama": "KOTA MADIUN", "kode": "D179"},
  {"nama": "KOTA MAGELANG", "kode": "D152"},
  {"nama": "KOTA MAKASSAR", "kode": "D398"},
  {"nama": "KOTA MALANG", "kode": "D180"},
  {"nama": "KOTA MANADO", "kode": "D456"},
  {"nama": "KOTA MATARAM", "kode": "D309"},
  {"nama": "KOTA MEDAN", "kode": "D502"},
  {"nama": "KOTA METRO", "kode": "D266"},
  {"nama": "KOTA MOJOKERTO", "kode": "D184"},
  {"nama": "KOTA PADANG", "kode": "D471"},
  {"nama": "KOTA PADANG PANJANG", "kode": "D469"},
  {"nama": "KOTA PADANGSIDIMPUAN", "kode": "D514"},
  {"nama": "KOTA PAGAR ALAM", "kode": "D484"},
  {"nama": "KOTA PALANGKARAYA", "kode": "D231"},
  {"nama": "KOTA PALEMBANG", "kode": "D486"},
  {"nama": "KOTA PALOPO", "kode": "D402"},
  {"nama": "KOTA PALU", "kode": "D425"},
  {"nama": "KOTA PANGKAL PINANG", "kode": "D38"},
  {"nama": "KOTA PARE PARE", "kode": "D403"},
  {"nama": "KOTA PARIAMAN", "kode": "D480"},
  {"nama": "KOTA PASURUAN", "kode": "D191"},
  {"nama": "KOTA PAYAKUMBUH", "kode": "D470"},
  {"nama": "KOTA PEKALONGAN", "kode": "D143"},
  {"nama": "KOTA PEKANBARU", "kode": "D377"},
  {"nama": "KOTA PEMATANGSIANTAR", "kode": "D515"},
  {"nama": "KOTA PONTIANAK", "kode": "D199"},
  {"nama": "KOTA PRABUMULIH", "kode": "D487"},
  {"nama": "KOTA PROBOLINGGO", "kode": "D188"},
  {"nama": "KOTA SABANG", "kode": "D7"},
  {"nama": "KOTA SALATIGA", "kode": "D148"},
  {"nama": "KOTA SAMARINDA", "kode": "D243"},
  {"nama": "KOTA SAWAHLUNTO", "kode": "D468"},
  {"nama": "KOTA SEMARANG", "kode": "D129"},
  {"nama": "KOTA SERANG", "kode": "D46"},
  {"nama": "KOTA SIBOLGA", "kode": "D531"},
  {"nama": "KOTA SINGKAWANG", "kode": "D200"},
  {"nama": "KOTA SOLOK", "kode": "D474"},
  {"nama": "KOTA SORONG", "kode": "D366"},
  {"nama": "KOTA SUBULUSSALAM", "kode": "D20"},
  {"nama": "KOTA SUKABUMI", "kode": "D104"},
  {"nama": "KOTA SUNGAI PENUH", "kode": "D91"},
  {"nama": "KOTA SURABAYA", "kode": "D181"},
  {"nama": "KOTA SURAKARTA", "kode": "D147"},
  {"nama": "KOTA TANGERANG", "kode": "D44"},
  {"nama": "KOTA TANGERANG SELATAN", "kode": "D47"},
  {"nama": "KOTA TANJUNG BALAI", "kode": "D501"},
  {"nama": "KOTA TANJUNG PINANG", "kode": "D259"},
  {"nama": "KOTA TARAKAN", "kode": "D245"},
  {"nama": "KOTA TASIKMALAYA", "kode": "D113"},
  {"nama": "KOTA TEBING TINGGI", "kode": "D516"},
  {"nama": "KOTA TEGAL", "kode": "D127"},
  {"nama": "KOTA TERNATE", "kode": "D293"},
  {"nama": "KOTA TIDORE KEPULAUAN", "kode": "D300"},
  {"nama": "KOTA TOMOHON", "kode": "D450"},
  {"nama": "KOTA TUAL", "kode": "D285"},
  {"nama": "KOTA YOGYAKARTA", "kode": "D64"}
];
