
name: Deploy React App
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: Preview_Web
        run: npm install
      - name: Build
        working-directory: Preview_Web
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Preview_Web/dist
          force_orphan: true
          cname: inaprocdata.agitstudio.cloud

