name: 🤖 Run Inaproc Sync Robot

on:
  schedule:
    - cron: '0 18 * * *' # Jam 01:00 WIB (18:00 UTC)
  workflow_dispatch: 

jobs:
  run-robot:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies (Langsung sebutkan modulnya)
        run: pip install pandas selenium

      - name: ⚙️ Konfigurasi Identitas Git
        run: |
          git config --global user.name "Inaproc Bot"
          git config --global user.email "bot@agitstudio.cloud"

      - name: 🔨 Run Robot (Otomatis Push di TAHAP 4)
        run: python MegaSyncInaproc.py